# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  buildActions:
    runs-on: ubuntu-latest

    steps:
      - name: Create variables for module cacher
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v3.5
        with:
          modules-to-cache: PsRunway

      - name: Run module cacher action
        id: cacher
        uses: actions/cache@v2
        with:
          path: ${{ steps.psmodulecache.outputs.modulepath }}
          key: ${{ steps.psmodulecache.outputs.keygen }}

      - name: Install PowerShell modules
        if: steps.cacher.outputs.cache-hit != 'true'
        uses: potatoqualitee/psmodulecache@v3.5

      - uses: actions/checkout@v2

      - name: Download runway.bin
        run: |
          wget https://runwaydownloads.blob.core.windows.net/appdl/runway.bin
          chmod +x ./runway.bin

      - name: Download any executables
        shell: pwsh
        run: ./repoScripts/replaceExecutables.ps1

      - name: Auth to Runway
        run: |
          ./runway.bin login -u ${{ secrets.RUNWAY_EMAIL }} -p ${{ secrets.RUNWAY_PASSWORD }}

      - name: Build Each Action on PR
        if: ${{ github.event_name == 'pull_request' }}
        shell: pwsh
        run: ./repoScripts/publish.ps1 -Test -RelativePath ./actions
      
      - name: Publish Each Action on Push
        if: ${{ github.event_name == 'push' }}
        shell: pwsh
        run: ./repoScripts/publish.ps1 -RelativePath ./actions
  
  buildJobs:
    runs-on: ubuntu-latest
    needs: buildActions

    steps:
      - uses: actions/checkout@v2

      - name: Create Jobs
        shell: pwsh
        run: ./jobs/script.ps1 -RunwayEmail ${{ secrets.RUNWAY_EMAIL }} -RunwayPassword ${{ secrets.RUNWAY_PASSWORD }}